name: lqliaa
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.3.0
  url_launcher: ^4.2.0+2
  google_fonts_arabic: ^1.1.7
  photo_view: ^0.3.1
  flutter_webview_plugin: ^0.3.0+2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/logo.png
   - assets/header_back.jpg
   - assets/Committees1.png
   - assets/Conseil1.png
   - assets/office1.png
   - assets/president1.png
   - assets/service1.png
   - assets/service2.png
   - assets/service3.png
   - assets/service4.png
   - assets/service5.png
   - assets/service6.png
   - assets/lqliaa_img_8.png
   - assets/homeNews1.jpg
   - assets/homeNews2.jpg
   - assets/homeNews3.jpg
   - assets/homeNews4.jpg
   - assets/lqliaa_img_1.jpg
   - assets/lqliaa_img_2.jpg
   - assets/lqliaa_img_3.jpg
   - assets/lqliaa_img_4.jpg
   - assets/lqliaa_img_5.jpg
   - assets/lqliaa_img_6.jpg
   - assets/lqliaa_img_7.jpg
   - assets/lqliaa_img_9.jpg
   - assets/lqliaa_img_10.jpg
   - assets/header_back1.png
   - assets/bureau1.png
   - assets/bureau2.png
   - assets/bureau3.png
   - assets/bureau4.png
   - assets/bureau5.png
   - assets/bureau6.png
   - assets/bureau7.png
   - assets/bureau8.png
   - assets/bureau9.png
   - assets/bureau10.png

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
